repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.19
  hooks:
  - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.2
  hooks:
  - id: ruff-check
    args: [ --fix ]
  - id: ruff-format
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: uv run pytest
    language: system
    pass_filenames: false
